//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillReport
    {
        public int BillNo { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> registrationFee { get; set; }
        public Nullable<int> c1 { get; set; }
        public Nullable<int> c2 { get; set; }
        public Nullable<int> c3 { get; set; }
        public Nullable<int> c4 { get; set; }
        public Nullable<int> c5 { get; set; }
        public Nullable<int> c6 { get; set; }
        public Nullable<int> c7 { get; set; }
        public Nullable<int> c8 { get; set; }
        public Nullable<int> c9 { get; set; }
        public Nullable<int> c10 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> AddGroup { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> c11 { get; set; }
    }
}
