//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FacilityInvoiceDetail
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public int FacilityId { get; set; }
        public int ServiceId { get; set; }
        public double Fee { get; set; }
        public double ServiceCharge { get; set; }
        public double Tax { get; set; }
        public Nullable<double> TaxPercent { get; set; }
        public double Discount { get; set; }
        public string DiscountType { get; set; }
    
        public virtual C_FacilityInvoice C_FacilityInvoice { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual FacilityItem FacilityItem { get; set; }
    }
}
