//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticCancelationDetail
    {
        public int SrNo { get; set; }
        public Nullable<int> RegistrationID { get; set; }
        public string CancelReason { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    }
}
