//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.BranchDoctors = new HashSet<BranchDoctor>();
            this.DoctorDegrees = new HashSet<DoctorDegree>();
            this.DoctorSpecializations = new HashSet<DoctorSpecialization>();
            this.RegistrationDoctors = new HashSet<RegistrationDoctor>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Fee { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Landline { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string DoctorVisitDay { get; set; }
        public string DoctorTiming { get; set; }
    
        public virtual ICollection<BranchDoctor> BranchDoctors { get; set; }
        public virtual ICollection<DoctorDegree> DoctorDegrees { get; set; }
        public virtual ICollection<DoctorSpecialization> DoctorSpecializations { get; set; }
        public virtual ICollection<RegistrationDoctor> RegistrationDoctors { get; set; }
    }
}
