//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.C_FacilityInvoiceDetail = new HashSet<C_FacilityInvoiceDetail>();
            this.FacilityItems = new HashSet<FacilityItem>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> FileId { get; set; }
        public bool UIVisible { get; set; }
        public bool MutlipleVisitRequired { get; set; }
    
        public virtual ICollection<C_FacilityInvoiceDetail> C_FacilityInvoiceDetail { get; set; }
        public virtual ICollection<FacilityItem> FacilityItems { get; set; }
    }
}
