//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliclinicPatnaEntities : DbContext
    {
        public PoliclinicPatnaEntities()
            : base("name=PoliclinicPatnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_FacilityInvoice> C_FacilityInvoice { get; set; }
        public DbSet<C_FacilityInvoiceDetail> C_FacilityInvoiceDetail { get; set; }
        public DbSet<AdminUser> AdminUsers { get; set; }
        public DbSet<BranchDoctor> BranchDoctors { get; set; }
        public DbSet<Degree> Degrees { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<DoctorDegree> DoctorDegrees { get; set; }
        public DbSet<DoctorSpecialization> DoctorSpecializations { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<FacilityItem> FacilityItems { get; set; }
        public DbSet<Registration> Registrations { get; set; }
        public DbSet<RegistrationDetail> RegistrationDetails { get; set; }
        public DbSet<RegistrationDoctor> RegistrationDoctors { get; set; }
        public DbSet<RegistrationFacility> RegistrationFacilities { get; set; }
        public DbSet<BillReport> BillReports { get; set; }
        public DbSet<DiagnosticCancelationDetail> DiagnosticCancelationDetails { get; set; }
        public DbSet<Specialization> Specializations { get; set; }
    }
}
