//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationFacility
    {
        public int Id { get; set; }
        public int RegistrationId { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int PaymentMethod { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string CancelReason { get; set; }
        public string CanceledBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public bool IsMultipleVisit { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
