//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public Registration()
        {
            this.RegistrationFacilities = new HashSet<RegistrationFacility>();
        }
    
        public int Id { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string RegNo { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
        public int PatientTypeId { get; set; }
        public int BranchId { get; set; }
        public bool IsActive { get; set; }
        public bool IsSingleBilling { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CanceledBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public int RegCount { get; set; }
        public Nullable<int> RecommendedBy { get; set; }
        public string RName { get; set; }
    
        public virtual RegistrationDetail RegistrationDetail { get; set; }
        public virtual ICollection<RegistrationFacility> RegistrationFacilities { get; set; }
    }
}
